name: Process YouTube Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "URL YouTube"
        required: true
        type: string

  repository_dispatch:
    types:
      - process_video

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Get YouTube URL
        id: video
        run: |
          if [ -n "${{ inputs.video_url }}" ]; then
            echo "url=${{ inputs.video_url }}" >> "$GITHUB_OUTPUT"
          else
            echo "url=${{ github.event.client_payload.video_url }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Get YouTube Video ID
        id: video_id
        run: |
          URL="${{ steps.video.outputs.url }}"

          VIDEO_ID=$(python3 -c "
          from urllib.parse import urlparse, parse_qs
          import sys

          url = sys.argv[1]
          p = urlparse(url)

          if 'youtu.be' in p.netloc:
              video_id = p.path.strip('/')
          elif 'youtube.com' in p.netloc:
              video_id = parse_qs(p.query).get('v', [''])[0]
          else:
              video_id = ''

          print(video_id)
          " "$URL")

          if [ -z "$VIDEO_ID" ]; then
            echo "Gagal menemukan YouTube Video ID"
            exit 1
          fi

          echo "Video ID: $VIDEO_ID"
          echo "id=$VIDEO_ID" >> "$GITHUB_OUTPUT"

      - name: Download YouTube thumbnail
        run: |
          VIDEO_ID="${{ steps.video_id.outputs.id }}"

          curl -L --fail \
            "https://i.ytimg.com/vi/${VIDEO_ID}/maxresdefault.jpg" \
            -o thumbnail-original.jpg

          if [ ! -s thumbnail-original.jpg ]; then
            echo "Max resolution thumbnail tidak tersedia."
            exit 1
          fi

      - name: Create square thumbnail
        run: |
          ffmpeg -y \
            -i thumbnail-original.jpg \
            -vf "scale=1080:1080:force_original_aspect_ratio=increase,crop=1080:1080" \
            -frames:v 1 \
            thumbnail.jpg

      - name: Check result
        run: |
          ls -lh thumbnail.jpg

          ffprobe \
            -v error \
            -show_entries stream=width,height \
            -of default=noprint_wrappers=1 \
            thumbnail.jpg

      - name: Save thumbnail
        uses: actions/upload-artifact@v4
        with:
          name: product-thumbnail
          path: thumbnail.jpg
